project_id = "xoaondyfwefdnuknlaix"

[functions.admin-users]
verify_jwt = true

[functions.generate-exercise]
verify_jwt = true

[functions.review-quiz-questions]
verify_jwt = true

[functions.assign-difficulty]
verify_jwt = true

[functions.generate-quiz-questions]
verify_jwt = true
