// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-courses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_courses_default = defineTool({
  name: "list_my_courses",
  title: "List my courses",
  description: "List the ESPOLMEDD courses the signed-in user has access to (title, description, id).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", userId);
    const isAdmin = (roles || []).some((r) => r.role === "admin");
    if (isAdmin) {
      const { data: data2, error: error2 } = await sb.from("cursos").select("id, titulo, descripcion").order("created_at");
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return { content: [{ type: "text", text: JSON.stringify(data2) }], structuredContent: { courses: data2 ?? [] } };
    }
    const { data: enroll, error: e1 } = await sb.from("curso_estudiantes").select("curso_id").eq("user_id", userId);
    if (e1) return { content: [{ type: "text", text: e1.message }], isError: true };
    const ids = (enroll ?? []).map((r) => r.curso_id);
    if (ids.length === 0) return { content: [{ type: "text", text: "[]" }], structuredContent: { courses: [] } };
    const { data, error } = await sb.from("cursos").select("id, titulo, descripcion").in("id", ids).order("created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { courses: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_sessions_default = defineTool2({
  name: "list_sessions",
  title: "List sessions in a course",
  description: "List learning sessions (number, title, topic) for a given course id.",
  inputSchema: {
    curso_id: z.string().uuid().describe("Course id (from list_my_courses).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ curso_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("sesiones").select("id, numero, titulo, tema").eq("curso_id", curso_id).order("numero");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { sessions: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_progress_default = defineTool3({
  name: "get_my_progress",
  title: "Get my progress",
  description: "Return the signed-in user's progress rows for a course (per-session completion, exercises, quiz hits).",
  inputSchema: {
    curso_id: z2.string().uuid().describe("Course id (from list_my_courses).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ curso_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await sb.from("progreso_estudiante").select("sesion_id, teoria_vista, ejercicios_correctos, quiz_aciertos, porcentaje, completado").eq("user_id", userId).eq("curso_id", curso_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { progress: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-recent-exams.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_exams_default = defineTool4({
  name: "list_recent_exams",
  title: "List my recent exam attempts",
  description: "Return the signed-in user's most recent exam history entries (type, score, date).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await sb.from("examen_historial").select("exam_tipo, correcta, created_at, pregunta_id").eq("user_id", userId).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { history: data ?? [] } };
  }
});

// src/lib/mcp/tools/whoami.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in ESPOLMEDD user profile (name, cedula, role).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser5(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      sb.from("profiles").select("nombre, cedula, avatar_url").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail?.() ?? null,
      nombre: profile?.nombre ?? null,
      cedula: profile?.cedula ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xoaondyfwefdnuknlaix";
var mcp_default = defineMcp({
  name: "espolmedd-mcp",
  title: "ESPOLMEDD",
  version: "0.1.0",
  instructions: "Tools for the ESPOLMEDD university-prep platform. Use `whoami` to identify the signed-in user, `list_my_courses` to discover courses, then `list_sessions` and `get_my_progress` for study state. `list_recent_exams` returns recent exam attempts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_courses_default, list_sessions_default, get_my_progress_default, list_recent_exams_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
